---
driver:
  name: ec2
  region: eu-west-1
  require_chef_omnibus: true
  instance_type: t2.micro
  #Subnet
  subnet_id: subnet-018e9e3078d34571c
  associate_public_ip: true
  aws_ssh_key_id: DevOpsStudents

  transport:
        #use our key from machine to access the test machine
        #ssh_key: ~/.ssh/rs-eng-42-class.pem

## The forwarded_port port feature lets you connect to ports on the VM guest via
## localhost on the host.
## see also: https://www.vagrantup.com/docs/networking/forwarded_ports.html

#  network:
#    - ["forwarded_port", {guest: 80, host: 8080}]

provisioner:
  name: chef_zero

  ## product_name and product_version specifies a specific Chef product and version to install.
  ## see the Chef documentation for more details: https://docs.chef.io/config_yml_kitchen.html
  #  product_name: chef
  #  product_version: 15

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
    driver:
      box: ubuntu/xenial64


suites:
  - name: default
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
